certmanager-issuer:
    email: "achansel@42.fr"
global:
    hosts:
        domain: achansel.com
    rails:
        bootsnap:
          enabled: false
    ingress:
        configureCertmanager: false
gitlab:
    webservice:
        minReplicas: 1
        maxReplicas: 1
    webservice:
        service:
            type: LoadBalancer
            loadBalancerSourceRanges: 
                - 172.30.33.193/20