Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end
  config.vm.provision "file", source: "confs/" , destination: "/home/vagrant/confs"
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "achanselS" do |s|
      s.vm.hostname = "achanselS"
      s.vm.network "private_network", ip: "192.168.56.110"
      s.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "anggonzaS"]
      end
      s.vm.provision "shell", path: "scripts/kubernetes.sh"
  end
end
